### ISSUE TITLE
Permission - protected variables

### ISSUE THREAD

**Issue by f3l1x** [nette/security#15]
For better extending I suggest to make [these variables](http://api.nette.org/2.3.4/source-Security.Permission.php.html#28,31,34) protected.

Is it ok? I'll prepare PR.

**Comment by JanTvrdik** [comment]
:-1: Why do you need that? There is a public API to manipulate rules in consistent manner.

**Comment by f3l1x** [comment]
I would like to change behavior of roles. Protected could solve it, I understand why is it private but also it's impossible extending.

**Comment by JanTvrdik** [comment]
> I would like to change behavior of roles.

That would probably violate [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle).
