### ISSUE TITLE
Logout callback

### ISSUE THREAD

**Issue by geniv** [nette/security#22]
- bug report? yes
- feature request? yes

in method logout(...) [https://github.com/nette/security/blob/master/src/Security/User.php#L99](https://github.com/nette/security/blob/master/src/Security/User.php#L99)
is wrong position callback: 

> $this->onLoggedOut($this);

if you want log out with this callback then callback will be called but identity did not clean, and this is wrong.
maybe will be write:
```
	public function logout($clearIdentity = FALSE)
	{
		if ($this->isLoggedIn()) {
			$this->storage->setAuthenticated(FALSE);
		        if ($clearIdentity) {
			      $this->storage->setIdentity(NULL);
		        }
                        $this->onLoggedOut($this);
		}
	}
```
like in method login(..., ...)

In documentation is this mistake:

> Událost $onLoggedIn je volána po úspěšném přihlášení, událost $onLoggedOut po odhlášení uživatele.

**Comment by CZechBoY** [comment]
and when user is not logged in, you really want to trigger onLoggedOut? 
i think current behaviour is correct.

**Comment by geniv** [comment]
@CZechBoY yes of course, I updated code, isLoggedIn is redundant call but yes it is for sure. All point it is in call method onLoggedOut like last one after cleared user storage, like method login() with set user storage

**Comment by CZechBoY** [comment]
OK, so now the point is to not clear storage if I'm not logged?

**Comment by geniv** [comment]
@CZechBoY hmm this is question, will be need clear storage if user does not logged? => identyty will be null or any data where also cleal with garbage collector/session clean mechanizm?

This problem is in used... for logging is actual position correct, but for correct logout and redirect is absolute wrong.

**Comment by CZechBoY** [comment]
So your problem is that you want to redirect in OnLoggedOut callback, but when you redirect you are still logged in - because setAuthenticate(false) is not called (because of exception/redirect). Right?

**Comment by geniv** [comment]
My target is in call OnLoggedOut had redirect after successfuly log out. In this case this code is not possible.

**Comment by geniv** [comment]
Yes, this problem as you write.

**Comment by dg** [comment]
You should not throw exceptions or exit app in handlers.

**Comment by geniv** [comment]
okey
