### ISSUE TITLE
Hidden dependency on nette/http

### ISSUE THREAD

**Issue by jiripudil** [nette/security#26]
- bug report? yes
- feature request? no
- version: 2.4.2

### Description

We have a project that uses Nette DI container, nette/bootstrap and nette/security, but not nette/http. However, nette/security secretly depends on nette/http when the DI component is present and nette/bootstrap's list of default extensions registers `SecurityExtension`:

```
Nette\DI\ServiceCreationException: Class Nette\Http\UserStorage used in service 'security.userStorage' not found.
```

### Steps To Reproduce

```sh
$ composer init
$ composer require nette/bootstrap nette/di nette/security
```

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$configurator = new Nette\Configurator();
$configurator->setTempDirectory(__DIR__ . '/tmp');
$configurator->createContainer();
```

### Possible solution

I think either nette/http has to be listed as a dependency in `require` section, or `SecurityExtension` must not register `Nette\Http\UserStorage` if nette/http is not installed. What do you think?

**Comment by JanTvrdik** [comment]
Imho there is no dependency on `Nette\Http\UserStorage`. There is `IUserStorage`. Feel free to use another implementation.

**Comment by Majkl578** [comment]
There is dependency in the DI bridge: https://github.com/nette/security/blob/f3824d56a72ce07d8e227c0c6039b0134c946aa8/src/Bridges/SecurityDI/SecurityExtension.php#L42
Also one reference is in README referencing UserStorage namespaces: https://github.com/nette/security/blob/18d47c6c6fd30a3b6702bf0fa4e16a399a4b7f92/readme.md#multiple-applications-in-one-scope (setNamespace() is not part of the interface) and in tests:

**Comment by JanTvrdik** [comment]
@Majkl578 That's not really a dependency. It's mostly a shortcut for common pattern. If the default factory was not provided, you would only get a different error message. If a different error message is the goal, feel free to go ahead and send a PR. But different error message is not a change of dependencies.

**Comment by jiripudil** [comment]
Funnily enough, we haven't seen any error until we first tried to go live with the app. Only then did the database migrations fail during the first deployment, because nette/http was missing from `--no-dev` build. Yep, turns out one of our dev dependencies indirectly requires nette/http, and thus we haven't found out about this earlier — everything was working just fine with dev dependencies installed.

> Feel free to use another implementation.

Thanks for pointing out, it seems obvious to me now that we were using this incorrectly. We've just been under the impression that it worked, because it did 🤷‍♂️ 

I could still imagine a situation, though, in which I'd only use, say, nette/security's ACL and wouldn't care at all about user storage. But SecurityExtension would be registered by nette/bootstrap, forcing me to supply my own NullUserStorage, which, in a particular coincidence, i'd only find out when deploying to production. That seems unfortunate.

Anyway, I'm not really sure how to tackle this, and I understand it's by far an edge case, so if you don't think it's worth the attention, so be it. At least someone googling the error message might stumble upon this issue and find help.

**Comment by JanTvrdik** [comment]
> I'm not really sure how to tackle this

It's seems that it's a problem of your test pipeline. You can for example install non-dev dependencies. compiler the container and run static analysis to make sure your code or the compiled container do not reference non-existing classes.

**Comment by jiripudil** [comment]
> Fixing one specific package does not solve the problem at all.

If the package is coupled to another package in runtime, yet does not list it in its dependencies, I thought it might at least help prevent the problem.

> You can for example install non-dev dependencies, compile the container and run static analysis to make sure your code or the compiled container do not reference non-existing classes.

To find out about an issue that I don't think is my fault in the first place. (sigh) But yes, I get the point about checking with the production set of dependencies.

---

Let's forget about this dev vs production dependency mixup and get back to the example I'd given:

> I could still imagine a situation, though, in which I'd only use, say, nette/security's ACL and **wouldn't care at all about user storage.** But SecurityExtension would be registered by nette/bootstrap, forcing me to supply my own NullUserStorage.

Do you think this is correct behaviour?

Even if so, I believe a more helpful error message would be a great enhancement. But that's where "I'm not really sure how to tackle this." If `SecurityExtension` threw an exception if `!class_exists(Nette\Http\UserStorage::class)`, it would still throw it even if I'd override the service definition later on in my config, right? Would a factory method be a viable option, that would return Nette\Http\UserStorage or throw a better worded exception, in runtime?

**Comment by JanTvrdik** [comment]
> If the package is coupled to another package in runtime

But it is not. The compiler extension is in `Bridges` namespace, which (by design) is not considered part of the package (i.e. `nette/security` does intentionally not require anything that's required for classes inside `Bridges` namespace). You're complaining here because of the `nette/http` dependency, but ignoring the fact that it also does not list dependency on `nette/di` and `tracy/tracy`.

> I don't think is my fault in the first place.

And I think it is you fault.

> Do you think this is correct behaviour?

Yes. Please understand that `SecurityExtension` is an optional part of `nette/security` package which implements common wiring strategy. It is not a goal `SecurityExtension` to support every possible wiring strategy.

> If SecurityExtension threw an exception if !class_exists(Nette\Http\UserStorage::class)

This is already done by `Nette\DI\Compiler`, there is not point of implementing this again in every compiler extension. Your problem is that your test pipeline does not properly isolate production and dev dependencies.

> Would a factory method be a viable option

That would make the entire situation about 10x worse. Instead of solving the problem it would just disable the compile time check, making the problem even harder to notice.

**Comment by jiripudil** [comment]
Ok, understood, thanks for your time.

**Comment by kb40505** [comment]
Remove my email and accounts
And whatever else is involved
