### ISSUE TITLE
Compatibility with non-nette apps?

### ISSUE THREAD

**Issue by tealborder** [nette/security#28]
- bug report? /no
- feature request? yes/no?

### Description
It would save a lot of time for me and other developers if the README mentioned something about compatibility of this lib with non-nette apps.
This way, I dont have to download it and check if I can use it as standalone lib.

**Comment by enumag** [comment]
Personal opinion: nette/security API is not ideal. I'd not recommend using it. I built [something](https://pehapkari.cz/blog/2017/08/14/arachne-security-separate-authentication-and-session-refresh/) [useful](https://pehapkari.cz/blog/2017/08/21/arachne-security-simplified-authorizator-and-fixed-acl-callbacks/) on top of it but then it's even more difficult to use standalone.

**Comment by tealborder** [comment]
@enumag Thanks! Good to know there's options. I'm closing this because I realized the README clearly states "Authentication & Authorization library for Nette." Cant believe I missed that as I was coming from packagist.org
