### ISSUE TITLE
cost and algorithm

### ISSUE THREAD

**Issue by mkoula** [nette/security#31]
Version: latest

### Bug Description
It's not a critical bug, but in `hash` method is used `PASSWORD_DEFAULT` constant and in `needsRehash` method is `PASSSWORD_BCRYPT`, it could maybe produce on php.ini settings some issues.

Also, the `cost` option is since PHP 7.0 deprecated.

As there's a possibility to use `PASSWORD_ARGON2I`since PHP 7.2, maybe the algorithm could be part of the method's input parameters?

I could try to implement it if you want and agree.

**Comment by dg** [comment]
I fixed needsRehash.

Deprecated is `salt`, not `cost`.

**Comment by mkoula** [comment]
True 😄 🙈, thanks
