### ISSUE TITLE
Passwords is incompatible with PHP 7.4 due to PHP BC break

### ISSUE THREAD

**Issue by JanTvrdik** [nette/security#35]
> Password hashing algorithm identifiers are now nullable strings rather than integers.
>
> * PASSWORD_DEFAULT was int 1; now is null
> * PASSWORD_BCRYPT was int 1; now is string '2y'
> * PASSWORD_ARGON2I was int 2; now is string 'argon2i'
> * PASSWORD_ARGON2ID was int 3; now is string 'argon2id'

> https://github.com/php/php-src/blob/39a0854307cd63685b2fe158207727a2b8c06cd7/UPGRADING#L120-L130

**Comment by dg** [comment]
I would wait if it does not change.

**Comment by JanTvrdik** [comment]
It has passed through RFC process (https://wiki.php.net/rfc/password_registry) and the BC break was explicitly mentioned so I think that change is unlikely.

**Comment by dg** [comment]
I think that this type of BC break was not mentioned.

**Comment by JanTvrdik** [comment]
It's explicitly mentioned in the [Backward Incompatible Changes](https://wiki.php.net/rfc/password_registry#backward_incompatible_changes) section of the RFC:

> Algorithm identifiers are now (nullable) strings rather than numbers.

It's further discussed in [Minimizing impact to BC](https://wiki.php.net/rfc/password_registry#minimizing_impact_to_bc) section of the RFC.

> In order to minimize the impact of the above BC. we could overload the password_hash() and password_needs_rehash() methods to accept integer values 0, 1, 2, and 3 to function as aliases for DEFAULT, BCRYPT, ARGIN2I, and ARGON2ID, respectively. Using an int would therefore work, but would produce a deprecation warning.

**Comment by dg** [comment]
But this is not related to this issue, or is it?

**Comment by JanTvrdik** [comment]
I don't understand the question, so instead I sent [PR](https://github.com/nette/security/pull/36) which [shows the issue](https://travis-ci.org/nette/security/jobs/553348225),

**Comment by dg** [comment]
I'm trying to say that in Backward Incompatible Changes section they didn't mention the case when a BC break arises because of the typehint is used in the userland code.

> Applications correctly using the constants such as PASSWORD_DEFAULT, PASSWORD_BCRYPT, etc… will continue to function correctly.

Nette\Security\Passwords correctly uses these constants but will not continue to work correctly.

ie. that the section is not exhaustive (Unlike for example are Nikita's RFC.)

So it is possible that over time it will appear that it breaks more code, and they change it (which is unlikely…).
