### ISSUE TITLE
Incompatibility with available nette/http in 3.1.1

### ISSUE THREAD

**Issue by jkavalik** [nette/security#54]
Argument 1 passed to Nette\Security\User::__construct() must be an instance of Nette\Security\UserStorage or null, instance of Nette\Http\UserStorage given, called in /core/Security/User.php on line 61 and defined in /vendor/nette/security/src/Security/User.php:66

probably nette/http v3.1.0-RC should not be RC anymore, but doing interface rename in a patch release seems a bit too aggressive anyway ;)

**Comment by jkavalik** [comment]
ah, I see 3.1.0 is tagged but not really released so it is not a simple patch release

**Comment by dg** [comment]
What exactly version od nette/http and nette/security do you have installed?

**Comment by jkavalik** [comment]
nette/security v3.1.1
nette/http v3.0.5

both are because
nette/nette v3.0.0 requires them with (^3.0)

**Comment by jkavalik** [comment]
and fixable by explicitly requiring
"nette/http": "3.1.0-RC"

**Comment by dg** [comment]
I can't make that bug on the sandbox…

**Comment by dg** [comment]
Feel free to send a repo or a sample code that doesn't work.

**Comment by jkavalik** [comment]
Does sandbox instantiate the security user service by default? We have it as a dependency for our logger.
We have our own implementation too which extends original `Nette\Security\User`, but the error is on the original constructor which we call (as our code still expects IUserStorage atm)

**Comment by jkavalik** [comment]
Hm, so the manually called constructor is at play here - it has strict order of arguments and pust the old IUserStorage instance where the UserStorage is expected
`$service = new Core\Security\User(true, $this->getService('security.userStorage'), null, null, $this->getService('orm.model'));`
(first parameter is our own, the rest is then sent to Nette\Security\User::__construct() )
whereas the DI itself in sandbox maps arguments by type, so it puts null into UserStorage and pust the 'security.userStorage' into IUserStorage $legacyStorage

**Comment by dg** [comment]
Yes, it instantiates user because it is Presenter dependency.

The problem will be that the constructor of the original User has changed https://github.com/nette/security/blob/f1cf0a120f7e3ba5f0014496b8a0a1d2d44d2ec8/src/Security/User.php#L66-L71 

Can you try this in master? 8da2aea68081fc02dd1b9648cefbb00a22e04a45

**Comment by jkavalik** [comment]
Yes, master fixed it

**Comment by dg** [comment]
Great

**Comment by jkavalik** [comment]
Thank you!
