### ISSUE TITLE
Passwords - Password strength detection

### ISSUE THREAD

**Issue by janbarasek** [nette/security#59]
Hello,

because Nette always relies on security, it would be a good idea to add a default way to verify the strength of your password (for example, in a form or anywhere in the application).

We can implement this as a method in Passwords with the interface `checkStrength(string $ password): int`, where the method returns the strength of the password as points from `0` (empty string) to `8` (best password).

All common rules should be checked as factors, such as:

- total password length
- types of characters (letters, numbers, case, special characters, characters of the national alphabet)
- common mistakes: capital letter at the beginning and number at the end
- use of one of the most common passwords from leaks (password of the "password" or "1234" type should get **0 points**, we can save, for example, the 100 most common ones directly in the array)

What do you think makes sense within a secure framework to provide a default way to protect applications? Nette Forms could immediately require a security level of at least 2 (8 characters, at least one number, and one character) for the ** password input**.

Thank you!

**Comment by milo** [comment]
Imho, this is not a task for Nette. It really hard to rank password entropy.

> use of one of the most common passwords
What about german, or french variants?

**Comment by mabar** [comment]
It's complicated enough to be a standalone library and really easy to create insecure implementation... 

e.g. [pam_passwdqc](https://www.openwall.com/passwdqc/) ([phplib](https://github.com/paragonie/passwdqc)) or [zxcvbn](https://github.com/dropbox/zxcvbn) ([phplib](https://github.com/bjeavons/zxcvbn-php)) based libraries are good choice

> most common passwords

Anything shipped with such common library will be mostly useless or enormous by size.
Probably [haveibeenpwned](https://haveibeenpwned.com/API/v3#PwnedPasswords) database with it's 12 GB of passwords is the best choice, but it should be purely optional
