### ISSUE TITLE
Nette Coding Standard test is broken

### ISSUE THREAD

**Issue by janbarasek** [nette/security#61]
Common coding standard test in this repo is broken: https://github.com/nette/security/pull/60/checks?check_run_id=2619233878

![Screenshot from 2021-05-19 12-33-24](https://user-images.githubusercontent.com/4738758/118798872-6abc4900-b89e-11eb-8c60-929e6b409f35.png)

Thanks.

**Comment by mabar** [comment]
Probably related to https://github.com/symplify/symplify/issues/3203

**Comment by dg** [comment]
Another one of the million BC breaks in symplify? That's a tragedy…  https://github.com/nette/coding-standard/commit/fd743fa9f60e10ee13e410c0395c5608be1ca2da
