### ISSUE TITLE
Flag `CLEAR_IDENTITY` is not present in `UserStorage`

### ISSUE THREAD

**Issue by simPod** [nette/security#62]
Version: 3.1

### Bug Description
`setExpiration()` says `Accepts flag IUserStorage::CLEAR_IDENTITY`

`IUserStorage` is deprecated in favor of `UserStorage`

`UserStorage` has no `CLEAR_IDENTITY` constant.

### Possible Solution

Introduce `CLEAR_IDENTITY` constant to `UserStorage`

**Comment by dg** [comment]
With the advent of named parameters in PHP, the preferred use will be `setExpiration(clearIdentity: true)`.
