### ISSUE TITLE
setExpiration: wrong argument type

### ISSUE THREAD

**Issue by Lumeriol** [nette/security#70]
Version: 4.0.x-dev and lower

### Bug Description
When I try to set User->setExpiration('30 minutes') with login form, there is type error in SessionStorage. Method setupExpiration() call $section->setExpiration() with local variable expireTime, that is typed as ?int, but first method argument must be ?string.

### Possible Solution
Change code on line 98 to

`$section->setExpiration((string)$this->expireTime, 'foo'); // time check`

**Comment by dg** [comment]
fixed
